name: Run cypress tests

on:
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: -- Node.js version - ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run build --if-present
    - run: npx cypress run
